### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by BWP09** [M10327/SurvivalLightBlocks#2]
It is producing these errors:
```
[14:30:54 ERROR]: Error occurred while enabling SurvivalLightBlocks v1.2 (Is it up to date?)
de.tr7zw.nbtapi.NbtApiException: [?]Exception while merging two NBTCompounds!
        at de.tr7zw.nbtapi.NBTReflectionUtil.mergeOtherNBTCompound(NBTReflectionUtil.java:383) ~[SurvivalLightBlocks_v1.2.jar:?]
        at de.tr7zw.nbtapi.NBTCompound.mergeCompound(NBTCompound.java:86) ~[SurvivalLightBlocks_v1.2.jar:?]
        at survivallightblocks.survivallightblocks.Utils.RecipeManager.addRecipe(RecipeManager.java:33) ~[SurvivalLightBlocks_v1.2.jar:?]
        at survivallightblocks.survivallightblocks.Utils.RecipeManager.<init>(RecipeManager.java:20) ~[SurvivalLightBlocks_v1.2.jar:?]
        at survivallightblocks.survivallightblocks.SurvivalLightBlocks.onEnable(SurvivalLightBlocks.java:15) ~[SurvivalLightBlocks_v1.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-49]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-49]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: de.tr7zw.nbtapi.NbtApiException: [?]Error while calling the method 'put(java.lang.String,net.minecraft.nbt.Tag)', loaded: true, Enum: COMPOUND_MERGE Passed Class: class java.lang.Boolean
        at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:185) ~[SurvivalLightBlocks_v1.2.jar:?]
        at de.tr7zw.nbtapi.NBTReflectionUtil.mergeOtherNBTCompound(NBTReflectionUtil.java:380) ~[SurvivalLightBlocks_v1.2.jar:?]
        ... 16 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@514141ed
        at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:183) ~[SurvivalLightBlocks_v1.2.jar:?]
        at de.tr7zw.nbtapi.NBTReflectionUtil.mergeOtherNBTCompound(NBTReflectionUtil.java:380) ~[SurvivalLightBlocks_v1.2.jar:?]
        ... 16 more
```
and
```
[14:30:54 ERROR]: Error occurred (in the plugin loader) while disabling SurvivalLightBlocks v1.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "survivallightblocks.survivallightblocks.Utils.RecipeManager.removeRecipe()" because "this.recipeManager" is null
        at survivallightblocks.survivallightblocks.SurvivalLightBlocks.onDisable(SurvivalLightBlocks.java:22) ~[SurvivalLightBlocks_v1.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-49]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-49]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-49]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by M10327** [comment]
What version of paper and nbt api are you using? I haven't updated this to 1.20 (and I don't know when I will) but that's likely the cause.
